version: "3.4"
x-shared-postgres-environment: &x-shared-postgres-environment
  POSTGRES_DB: "${POSTGRES_DB:-mutualaid}"
  POSTGRES_USER: "${POSTGRES_USER:-postgres}"
  # this variable should be set in a .env file or passed via the docker-compose cli
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

x-shared-environment-defaults:
  - &APP_PORT "${APP_PORT:-3000}"
  - &EMAIL_PORT "${EMAIL_PORT:-1080}"

x-email-defaults: &x-email-defaults
  EMAIL_PORT: *EMAIL_PORT
  EMAIL_HOST: "${EMAIL_HOST:-email}"
  EMAIL_FROM_ADDR: "${EMAIL_FROM_ADDR:-\"mutualaid@localhost\"}"
  EMAIL_DEFAULT_URL_HOST: "${EMAIL_DEFAULT_URL_HOST:-\"localhost:3000\"}"

services:
  email:
    build:
      context: .
      dockerfile: ./email/Dockerfile
    depends_on:
      - db
    ports:
      - target: 1080
        published: *EMAIL_PORT
  db:
    image: postgres:alpine
    environment:
      <<: *x-shared-postgres-environment
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build:
      context: ../..
      dockerfile: ./docker/development/app/Dockerfile
      args:
        APP_PORT: *APP_PORT
    ports:
      - target: *APP_PORT
        published: *APP_PORT
    depends_on:
      - db
      - email
    environment:
      <<: *x-shared-postgres-environment
      <<: *x-email-defaults
      RAILS_ENV: docker-development
      POSTGRES_HOST: db
      # You can set this by running
      # rake secret
      # The resulting key should be placed in a .env file
      # in this directory, or you can pass it to
      # docker-compose up --build -e SECRET_KEY_BASE=...
      # Otherwise the database setup step will fail
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
volumes:
  db:
