require 'rails_helper'
require_relative '../support/devise'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/categories", type: :request do
  # Category. As you add validations to Category, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "admin user can" do
    login_admin

    context "GET /index" do
      it "renders a successful response" do
        Category.create! valid_attributes
        get categories_url
        expect(response).to be_successful
      end
    end

    context "GET /show" do
      it "renders a successful response" do
        category = Category.create! valid_attributes
        get category_url(category)
        expect(response).to be_successful
      end
    end

    context "GET /new" do
      it "renders a successful response" do
        get new_category_url
        expect(response).to be_successful
      end
    end

    context "GET /edit" do
      it "render a successful response" do
        category = Category.create! valid_attributes
        get edit_category_url(category)
        expect(response).to be_successful
      end
    end

    context "POST /create" do
      context "with valid parameters" do
        it "creates a new Category" do
          expect {
            post categories_url, params: { category: valid_attributes }
          }.to change(Category, :count).by(1)
        end

        it "redirects to the created category" do
          post categories_url, params: { category: valid_attributes }
          expect(response).to redirect_to(category_url(Category.last))
        end
      end

      context "with invalid parameters" do
        it "does not create a new Category" do
          expect {
            post categories_url, params: { category: invalid_attributes }
          }.to change(Category, :count).by(0)
        end

        it "renders a successful response (i.e. to display the 'new' template)" do
          post categories_url, params: { category: invalid_attributes }
          expect(response).to be_successful
        end
      end
    end

    context "PATCH /update" do
      context "with valid parameters" do
        let(:new_attributes) {
          skip("Add a hash of attributes valid for your model")
        }

        it "updates the requested category" do
          category = Category.create! valid_attributes
          patch category_url(category), params: { category: new_attributes }
          category.reload
          skip("Add assertions for updated state")
        end

        it "redirects to the category" do
          category = Category.create! valid_attributes
          patch category_url(category), params: { category: new_attributes }
          category.reload
          expect(response).to redirect_to(category_url(category))
        end
      end

      context "with invalid parameters" do
        it "renders a successful response (i.e. to display the 'edit' template)" do
          category = Category.create! valid_attributes
          patch category_url(category), params: { category: invalid_attributes }
          expect(response).to be_successful
        end
      end
    end

    context "DELETE /destroy" do
      it "destroys the requested category" do
        category = Category.create! valid_attributes
        expect {
          delete category_url(category)
        }.to change(Category, :count).by(-1)
      end

      it "redirects to the categories list" do
        category = Category.create! valid_attributes
        delete category_url(category)
        expect(response).to redirect_to(categories_url)
      end
    end
  end

  describe "non-admin user can" do
    login_user

    context "GET /index" do
      it "renders a successful response" do
        Category.create! valid_attributes
        get categories_url
        expect(response).to be_successful
      end
    end

    context "GET /show" do
      it "renders a successful response" do
        category = Category.create! valid_attributes
        get category_url(category)
        expect(response).to be_successful
      end
    end

    context "GET /new" do
      it "renders a successful response" do
        get new_category_url
        expect(response).to be_successful
      end
    end

    context "GET /edit" do
      it "render a successful response" do
        category = Category.create! valid_attributes
        get edit_category_url(category)
        expect(response).to be_successful
      end
    end

    context "POST /create" do
      context "with valid parameters" do
        it "creates a new Category" do
          expect {
            post categories_url, params: { category: valid_attributes }
          }.to change(Category, :count).by(1)
        end

        it "redirects to the created category" do
          post categories_url, params: { category: valid_attributes }
          expect(response).to redirect_to(category_url(Category.last))
        end
      end

      context "with invalid parameters" do
        it "does not create a new Category" do
          expect {
            post categories_url, params: { category: invalid_attributes }
          }.to change(Category, :count).by(0)
        end

        it "renders a successful response (i.e. to display the 'new' template)" do
          post categories_url, params: { category: invalid_attributes }
          expect(response).to be_successful
        end
      end
    end

    context "PATCH /update" do
      context "with valid parameters" do
        let(:new_attributes) {
          skip("Add a hash of attributes valid for your model")
        }

        it "updates the requested category" do
          category = Category.create! valid_attributes
          patch category_url(category), params: { category: new_attributes }
          category.reload
          skip("Add assertions for updated state")
        end

        it "redirects to the category" do
          category = Category.create! valid_attributes
          patch category_url(category), params: { category: new_attributes }
          category.reload
          expect(response).to redirect_to(category_url(category))
        end
      end

      context "with invalid parameters" do
        it "renders a successful response (i.e. to display the 'edit' template)" do
          category = Category.create! valid_attributes
          patch category_url(category), params: { category: invalid_attributes }
          expect(response).to be_successful
        end
      end
    end

    context "DELETE /destroy" do
      it "destroys the requested category" do
        category = Category.create! valid_attributes
        expect {
          delete category_url(category)
        }.to change(Category, :count).by(-1)
      end

      it "redirects to the categories list" do
        category = Category.create! valid_attributes
        delete category_url(category)
        expect(response).to redirect_to(categories_url)
      end
    end
  end

  describe "not authenticated user can" do

    context "GET /index" do
      it "renders a successful response" do
        Category.create! valid_attributes
        get categories_url
        expect(response).to_not be_successful
      end
    end

    context "GET /show" do
      it "renders a successful response" do
        category = Category.create! valid_attributes
        get category_url(category)
        expect(response).to_not be_successful
      end
    end

    context "GET /new" do
      it "renders a successful response" do
        get new_category_url
        expect(response).to_not be_successful
      end
    end

    context "GET /edit" do
      it "render a successful response" do
        category = Category.create! valid_attributes
        get edit_category_url(category)
        expect(response).to_not be_successful
      end
    end

    context "POST /create" do
      context "with valid parameters" do
        it "creates a new Category" do
          expect {
            post categories_url, params: { category: valid_attributes }
          }.to change(Category, :count).by(1)
        end

        it "redirects to the created category" do
          post categories_url, params: { category: valid_attributes }
          expect(response).to redirect_to(category_url(Category.last))
        end
      end

      context "with invalid parameters" do
        it "does not create a new Category" do
          expect {
            post categories_url, params: { category: invalid_attributes }
          }.to change(Category, :count).by(0)
        end

        it "renders a successful response (i.e. to display the 'new' template)" do
          post categories_url, params: { category: invalid_attributes }
          expect(response).to be_successful
        end
      end
    end

    context "PATCH /update" do
      context "with valid parameters" do
        let(:new_attributes) {
          skip("Add a hash of attributes valid for your model")
        }

        it "updates the requested category" do
          category = Category.create! valid_attributes
          patch category_url(category), params: { category: new_attributes }
          category.reload
          skip("Add assertions for updated state")
        end

        it "redirects to the category" do
          category = Category.create! valid_attributes
          patch category_url(category), params: { category: new_attributes }
          category.reload
          expect(response).to redirect_to(category_url(category))
        end
      end

      context "with invalid parameters" do
        it "renders a successful response (i.e. to display the 'edit' template)" do
          category = Category.create! valid_attributes
          patch category_url(category), params: { category: invalid_attributes }
          expect(response).to be_successful
        end
      end
    end

    context "DELETE /destroy" do
      it "destroys the requested category" do
        category = Category.create! valid_attributes
        expect {
          delete category_url(category)
        }.to change(Category, :count).by(-1)
      end

      it "redirects to the categories list" do
        category = Category.create! valid_attributes
        delete category_url(category)
        expect(response).to redirect_to(categories_url)
      end
    end
  end
end
