 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/expense_types", type: :request do
  # ExpenseType. As you add validations to ExpenseType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ExpenseType.create! valid_attributes
      get expense_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      expense_type = ExpenseType.create! valid_attributes
      get expense_type_url(expense_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_expense_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      expense_type = ExpenseType.create! valid_attributes
      get edit_expense_type_url(expense_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ExpenseType" do
        expect {
          post expense_types_url, params: { expense_type: valid_attributes }
        }.to change(ExpenseType, :count).by(1)
      end

      it "redirects to the created expense_type" do
        post expense_types_url, params: { expense_type: valid_attributes }
        expect(response).to redirect_to(expense_type_url(ExpenseType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ExpenseType" do
        expect {
          post expense_types_url, params: { expense_type: invalid_attributes }
        }.to change(ExpenseType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post expense_types_url, params: { expense_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested expense_type" do
        expense_type = ExpenseType.create! valid_attributes
        patch expense_type_url(expense_type), params: { expense_type: new_attributes }
        expense_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the expense_type" do
        expense_type = ExpenseType.create! valid_attributes
        patch expense_type_url(expense_type), params: { expense_type: new_attributes }
        expense_type.reload
        expect(response).to redirect_to(expense_type_url(expense_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        expense_type = ExpenseType.create! valid_attributes
        patch expense_type_url(expense_type), params: { expense_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested expense_type" do
      expense_type = ExpenseType.create! valid_attributes
      expect {
        delete expense_type_url(expense_type)
      }.to change(ExpenseType, :count).by(-1)
    end

    it "redirects to the expense_types list" do
      expense_type = ExpenseType.create! valid_attributes
      delete expense_type_url(expense_type)
      expect(response).to redirect_to(expense_types_url)
    end
  end
end
