 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/forms", type: :request do
  # Form. As you add validations to Form, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Form.create! valid_attributes
      get forms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      form = Form.create! valid_attributes
      get form_url(form)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_form_url
      skip
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      form = Form.create! valid_attributes
      get edit_form_url(form)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Form" do
        expect {
          post forms_url, params: { form: valid_attributes }
        }.to change(Form, :count).by(1)
      end

      it "redirects to the created form" do
        post forms_url, params: { form: valid_attributes }
        expect(response).to redirect_to(form_url(Form.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Form" do
        expect {
          post forms_url, params: { form: invalid_attributes }
        }.to change(Form, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post forms_url, params: { form: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested form" do
        form = Form.create! valid_attributes
        patch form_url(form), params: { form: new_attributes }
        form.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the form" do
        form = Form.create! valid_attributes
        patch form_url(form), params: { form: new_attributes }
        form.reload
        expect(response).to redirect_to(form_url(form))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        form = Form.create! valid_attributes
        patch form_url(form), params: { form: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested form" do
      form = Form.create! valid_attributes
      expect {
        delete form_url(form)
      }.to change(Form, :count).by(-1)
    end

    it "redirects to the forms list" do
      form = Form.create! valid_attributes
      delete form_url(form)
      expect(response).to redirect_to(forms_url)
    end
  end
end
