 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mobility_string_translations", type: :request do
  # MobilityStringTranslation. As you add validations to MobilityStringTranslation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MobilityStringTranslation.create! valid_attributes
      get mobility_string_translations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mobility_string_translation = MobilityStringTranslation.create! valid_attributes
      get mobility_string_translation_url(mobility_string_translation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      skip # TODO - /new needs to work with view_header
      get new_mobility_string_translation_url(test_action_name: "new", test_controller_name: "mobility_string_translations")
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      mobility_string_translation = MobilityStringTranslation.create! valid_attributes
      get edit_mobility_string_translation_url(mobility_string_translation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MobilityStringTranslation" do
        expect {
          post mobility_string_translations_url, params: { mobility_string_translation: valid_attributes }
        }.to change(MobilityStringTranslation, :count).by(1)
      end

      it "redirects to the created mobility_string_translation" do
        post mobility_string_translations_url, params: { mobility_string_translation: valid_attributes }
        expect(response).to redirect_to(mobility_string_translation_url(MobilityStringTranslation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MobilityStringTranslation" do
        expect {
          post mobility_string_translations_url, params: { mobility_string_translation: invalid_attributes }
        }.to change(MobilityStringTranslation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post mobility_string_translations_url, params: { mobility_string_translation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mobility_string_translation" do
        mobility_string_translation = MobilityStringTranslation.create! valid_attributes
        patch mobility_string_translation_url(mobility_string_translation), params: { mobility_string_translation: new_attributes }
        mobility_string_translation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mobility_string_translation" do
        mobility_string_translation = MobilityStringTranslation.create! valid_attributes
        patch mobility_string_translation_url(mobility_string_translation), params: { mobility_string_translation: new_attributes }
        mobility_string_translation.reload
        expect(response).to redirect_to(mobility_string_translation_url(mobility_string_translation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        mobility_string_translation = MobilityStringTranslation.create! valid_attributes
        patch mobility_string_translation_url(mobility_string_translation), params: { mobility_string_translation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mobility_string_translation" do
      mobility_string_translation = MobilityStringTranslation.create! valid_attributes
      expect {
        delete mobility_string_translation_url(mobility_string_translation)
      }.to change(MobilityStringTranslation, :count).by(-1)
    end

    it "redirects to the mobility_string_translations list" do
      mobility_string_translation = MobilityStringTranslation.create! valid_attributes
      delete mobility_string_translation_url(mobility_string_translation)
      expect(response).to redirect_to(mobility_string_translations_url)
    end
  end
end
