 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/shifts", type: :request do
  # Shift. As you add validations to Shift, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Shift.create! valid_attributes
      get shifts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      shift = Shift.create! valid_attributes
      get shift_url(shift)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_shift_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      shift = Shift.create! valid_attributes
      get edit_shift_url(shift)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Shift" do
        expect {
          post shifts_url, params: { shift: valid_attributes }
        }.to change(Shift, :count).by(1)
      end

      it "redirects to the created shift" do
        post shifts_url, params: { shift: valid_attributes }
        expect(response).to redirect_to(shift_url(Shift.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Shift" do
        expect {
          post shifts_url, params: { shift: invalid_attributes }
        }.to change(Shift, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post shifts_url, params: { shift: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested shift" do
        shift = Shift.create! valid_attributes
        patch shift_url(shift), params: { shift: new_attributes }
        shift.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the shift" do
        shift = Shift.create! valid_attributes
        patch shift_url(shift), params: { shift: new_attributes }
        shift.reload
        expect(response).to redirect_to(shift_url(shift))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        shift = Shift.create! valid_attributes
        patch shift_url(shift), params: { shift: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested shift" do
      shift = Shift.create! valid_attributes
      expect {
        delete shift_url(shift)
      }.to change(Shift, :count).by(-1)
    end

    it "redirects to the shifts list" do
      shift = Shift.create! valid_attributes
      delete shift_url(shift)
      expect(response).to redirect_to(shifts_url)
    end
  end
end
