 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/submissions", type: :request do
  # Submission. As you add validations to Submission, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Submission.create! valid_attributes
      get submissions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      submission = Submission.create! valid_attributes
      get submission_url(submission)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_submission_url
      skip
      # expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      submission = Submission.create! valid_attributes
      get edit_submission_url(submission)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Submission" do
        expect {
          post submissions_url, params: { submission: valid_attributes }
        }.to change(Submission, :count).by(1)
      end

      it "redirects to the created submission" do
        post submissions_url, params: { submission: valid_attributes }
        expect(response).to redirect_to(submission_url(Submission.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Submission" do
        expect {
          post submissions_url, params: { submission: invalid_attributes }
        }.to change(Submission, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post submissions_url, params: { submission: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested submission" do
        submission = Submission.create! valid_attributes
        patch submission_url(submission), params: { submission: new_attributes }
        submission.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the submission" do
        submission = Submission.create! valid_attributes
        patch submission_url(submission), params: { submission: new_attributes }
        submission.reload
        expect(response).to redirect_to(submission_url(submission))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        submission = Submission.create! valid_attributes
        patch submission_url(submission), params: { submission: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested submission" do
      submission = Submission.create! valid_attributes
      expect {
        delete submission_url(submission)
      }.to change(Submission, :count).by(-1)
    end

    it "redirects to the submissions list" do
      submission = Submission.create! valid_attributes
      delete submission_url(submission)
      expect(response).to redirect_to(submissions_url)
    end
  end
end
