 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/system_locales", type: :request do
  # SystemLocale. As you add validations to SystemLocale, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SystemLocale.create! valid_attributes
      get system_locales_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      system_locale = SystemLocale.create! valid_attributes
      get system_locale_url(system_locale)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      skip # TODO
      get new_system_locale_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      system_locale = SystemLocale.create! valid_attributes
      get edit_system_locale_url(system_locale)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SystemLocale" do
        expect {
          post system_locales_url, params: { system_locale: valid_attributes }
        }.to change(SystemLocale, :count).by(1)
      end

      it "redirects to the created system_locale" do
        post system_locales_url, params: { system_locale: valid_attributes }
        expect(response).to redirect_to(system_locale_url(SystemLocale.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SystemLocale" do
        expect {
          post system_locales_url, params: { system_locale: invalid_attributes }
        }.to change(SystemLocale, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post system_locales_url, params: { system_locale: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested system_locale" do
        system_locale = SystemLocale.create! valid_attributes
        patch system_locale_url(system_locale), params: { system_locale: new_attributes }
        system_locale.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the system_locale" do
        system_locale = SystemLocale.create! valid_attributes
        patch system_locale_url(system_locale), params: { system_locale: new_attributes }
        system_locale.reload
        expect(response).to redirect_to(system_locale_url(system_locale))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        system_locale = SystemLocale.create! valid_attributes
        patch system_locale_url(system_locale), params: { system_locale: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested system_locale" do
      system_locale = SystemLocale.create! valid_attributes
      expect {
        delete system_locale_url(system_locale)
      }.to change(SystemLocale, :count).by(-1)
    end

    it "redirects to the system_locales list" do
      system_locale = SystemLocale.create! valid_attributes
      delete system_locale_url(system_locale)
      expect(response).to redirect_to(system_locales_url)
    end
  end
end
