 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/system_tags", type: :request do
  # SystemTag. As you add validations to SystemTag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SystemTag.create! valid_attributes
      get system_tags_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      system_tag = SystemTag.create! valid_attributes
      get system_tag_url(system_tag)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_system_tag_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      system_tag = SystemTag.create! valid_attributes
      get edit_system_tag_url(system_tag)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SystemTag" do
        expect {
          post system_tags_url, params: { system_tag: valid_attributes }
        }.to change(SystemTag, :count).by(1)
      end

      it "redirects to the created system_tag" do
        post system_tags_url, params: { system_tag: valid_attributes }
        expect(response).to redirect_to(system_tag_url(SystemTag.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SystemTag" do
        expect {
          post system_tags_url, params: { system_tag: invalid_attributes }
        }.to change(SystemTag, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post system_tags_url, params: { system_tag: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested system_tag" do
        system_tag = SystemTag.create! valid_attributes
        patch system_tag_url(system_tag), params: { system_tag: new_attributes }
        system_tag.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the system_tag" do
        system_tag = SystemTag.create! valid_attributes
        patch system_tag_url(system_tag), params: { system_tag: new_attributes }
        system_tag.reload
        expect(response).to redirect_to(system_tag_url(system_tag))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        system_tag = SystemTag.create! valid_attributes
        patch system_tag_url(system_tag), params: { system_tag: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested system_tag" do
      system_tag = SystemTag.create! valid_attributes
      expect {
        delete system_tag_url(system_tag)
      }.to change(SystemTag, :count).by(-1)
    end

    it "redirects to the system_tags list" do
      system_tag = SystemTag.create! valid_attributes
      delete system_tag_url(system_tag)
      expect(response).to redirect_to(system_tags_url)
    end
  end
end
