class AddAutoGeneratedToCommunicationLog < ActiveRecord::Migration[6.0]
  def up
    add_column :communication_logs, :auto_generated, :boolean
    change_column_default :communication_logs, :auto_generated, false
  end

  def down
    remove_column :communication_logs, :auto_generated
  end
end
